<?php

namespace Database\Seeders;

use App\Models\Supplier;
use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        $suppliers = [
            [
                'name' => 'Nairobi Fresh Foods Ltd',
                'supplier_code' => 'NFF001',
                'description' => 'Fresh vegetables, fruits, and produce supplier',
                'contact_person' => 'James Mwangi',
                'phone' => '+254722123456',
                'email' => 'orders@nairobifreshfoods.co.ke',
                'address' => 'Wakulima Market, Nairobi',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'tax_number' => 'P051234567A',
                'payment_terms' => ['net_days' => 30, 'discount_days' => 10, 'discount_percentage' => 2],
                'credit_limit' => 50000,
                'supplier_type' => 'wholesale',
                'average_delivery_days' => 1,
                'reliability_rating' => 'excellent',
                'notes' => 'Reliable supplier for fresh produce. Daily deliveries available.',
                'is_active' => true,
            ],
            [
                'name' => 'Kenya Meat Processors',
                'supplier_code' => 'KMP002',
                'description' => 'Quality meat and poultry supplier',
                'contact_person' => 'Mary Wanjiku',
                'phone' => '+254733987654',
                'email' => 'sales@kenyameat.co.ke',
                'address' => 'Industrial Area, Nairobi',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'tax_number' => 'P051234568B',
                'payment_terms' => ['net_days' => 21, 'discount_days' => 7, 'discount_percentage' => 1.5],
                'credit_limit' => 75000,
                'supplier_type' => 'wholesale',
                'average_delivery_days' => 1,
                'reliability_rating' => 'excellent',
                'notes' => 'HACCP certified. Weekly deliveries on Mondays and Thursdays.',
                'is_active' => true,
            ],
            [
                'name' => 'Brookside Dairy Ltd',
                'supplier_code' => 'BDL003',
                'description' => 'Dairy products and milk supplier',
                'contact_person' => 'Peter Kimani',
                'phone' => '+254722456789',
                'email' => 'orders@brookside.co.ke',
                'address' => 'Ruiru, Kiambu County',
                'city' => 'Ruiru',
                'country' => 'Kenya',
                'tax_number' => 'P051234569C',
                'payment_terms' => ['net_days' => 14, 'discount_days' => 5, 'discount_percentage' => 2],
                'credit_limit' => 30000,
                'supplier_type' => 'wholesale',
                'average_delivery_days' => 2,
                'reliability_rating' => 'good',
                'notes' => 'Daily deliveries for milk, weekly for other dairy products.',
                'is_active' => true,
            ],
            [
                'name' => 'Bidco Oil Refineries',
                'supplier_code' => 'BOR004',
                'description' => 'Cooking oils and fats supplier',
                'contact_person' => 'Grace Mutinda',
                'phone' => '+254755123456',
                'email' => 'sales@bidcoafrica.com',
                'address' => 'Thika Road, Nairobi',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'tax_number' => 'P051234570D',
                'payment_terms' => ['net_days' => 30, 'discount_days' => 0, 'discount_percentage' => 0],
                'credit_limit' => 40000,
                'supplier_type' => 'wholesale',
                'average_delivery_days' => 3,
                'reliability_rating' => 'good',
                'notes' => 'Bulk orders preferred. Monthly delivery schedule.',
                'is_active' => true,
            ],
            [
                'name' => 'Coca Cola Bottlers Kenya',
                'supplier_code' => 'CCK005',
                'description' => 'Soft drinks and beverages supplier',
                'contact_person' => 'Samuel Ochieng',
                'phone' => '+254766789123',
                'email' => 'orders@coke.co.ke',
                'address' => 'Upper Hill, Nairobi',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'tax_number' => 'P051234571E',
                'payment_terms' => ['net_days' => 15, 'discount_days' => 0, 'discount_percentage' => 0],
                'credit_limit' => 60000,
                'supplier_type' => 'wholesale',
                'average_delivery_days' => 2,
                'reliability_rating' => 'excellent',
                'notes' => 'Weekly deliveries. Credit terms available for bulk orders.',
                'is_active' => true,
            ],
            [
                'name' => 'Kapa Oil Refineries',
                'supplier_code' => 'KOR006',
                'description' => 'Cooking oil and margarine supplier',
                'contact_person' => 'David Mutua',
                'phone' => '+254777888999',
                'email' => 'sales@kapaoil.co.ke',
                'address' => 'Nakuru',
                'city' => 'Nakuru',
                'country' => 'Kenya',
                'tax_number' => 'P051234572F',
                'payment_terms' => ['net_days' => 30, 'discount_days' => 15, 'discount_percentage' => 2.5],
                'credit_limit' => 35000,
                'supplier_type' => 'wholesale',
                'average_delivery_days' => 4,
                'reliability_rating' => 'good',
                'notes' => 'Competitive pricing on bulk orders. Bi-weekly deliveries.',
                'is_active' => true,
            ],
            [
                'name' => 'Chandaria Industries (Packaging)',
                'supplier_code' => 'CHI007',
                'description' => 'Take-away packaging and disposables',
                'contact_person' => 'Rachel Njeri',
                'phone' => '+254788999000',
                'email' => 'orders@chandaria.co.ke',
                'address' => 'Industrial Area, Nairobi',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'tax_number' => 'P051234573G',
                'payment_terms' => ['net_days' => 45, 'discount_days' => 10, 'discount_percentage' => 3],
                'credit_limit' => 25000,
                'supplier_type' => 'wholesale',
                'average_delivery_days' => 5,
                'reliability_rating' => 'good',
                'notes' => 'Custom packaging options available. Monthly orders preferred.',
                'is_active' => true,
            ],
            [
                'name' => 'Unilever Kenya Ltd',
                'supplier_code' => 'UNI008',
                'description' => 'Cleaning supplies and detergents',
                'contact_person' => 'Alice Wambui',
                'phone' => '+254799000111',
                'email' => 'kenya.orders@unilever.com',
                'address' => 'Upper Hill, Nairobi',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'tax_number' => 'P051234574H',
                'payment_terms' => ['net_days' => 30, 'discount_days' => 0, 'discount_percentage' => 0],
                'credit_limit' => 20000,
                'supplier_type' => 'wholesale',
                'average_delivery_days' => 3,
                'reliability_rating' => 'excellent',
                'notes' => 'Premium cleaning products. Quarterly orders recommended.',
                'is_active' => true,
            ],
        ];

        foreach ($suppliers as $supplier) {
            Supplier::create($supplier);
        }
    }
}